package cloudsnorkelcdkgithubrunners


// Options for fast launch.
// Experimental.
type FastLaunchOptions struct {
	// Enable fast launch for AMIs generated by this builder.
	//
	// It creates a snapshot of the root volume and uses it to launch new instances faster.
	//
	// This is only supported for Windows AMIs.
	// Default: false.
	//
	// Experimental.
	Enabled *bool `field:"optional" json:"enabled" yaml:"enabled"`
	// The maximum number of parallel instances that are launched for creating resources.
	//
	// Must be at least 6.
	// Default: 6.
	//
	// Experimental.
	MaxParallelLaunches *float64 `field:"optional" json:"maxParallelLaunches" yaml:"maxParallelLaunches"`
	// The number of pre-provisioned snapshots to keep on hand for a fast-launch enabled Windows AMI.
	// Default: 1.
	//
	// Experimental.
	TargetResourceCount *float64 `field:"optional" json:"targetResourceCount" yaml:"targetResourceCount"`
}

