package cloudsnorkelcdkgithubrunners

import (
	_jsii_ "github.com/aws/jsii-runtime-go/runtime"
	_init_ "github.com/CloudSnorkel/cdk-github-runners-go/cloudsnorkelcdkgithubrunners/jsii"

	"github.com/aws/aws-cdk-go/awscdk/v2"
	"github.com/aws/aws-cdk-go/awscdk/v2/awsiam"
	"github.com/aws/aws-cdk-go/awscdk/v2/interfaces"
	"github.com/aws/constructs-go/constructs/v10"
	"github.com/CloudSnorkel/cdk-github-runners-go/cloudsnorkelcdkgithubrunners/internal"
)

// Components are a set of commands to run and optional files to add to an image.
//
// Components are the building blocks of images built by Image Builder.
//
// Example:
//
// ```
// new ImageBuilderComponent(this, 'AWS CLI', {
//   platform: 'Windows',
//   displayName: 'AWS CLI',
//   description: 'Install latest version of AWS CLI',
//   commands: [
//     '$p = Start-Process msiexec.exe -PassThru -Wait -ArgumentList \'/i https://awscli.amazonaws.com/AWSCLIV2.msi /qn\'',
//     'if ($p.ExitCode -ne 0) { throw "Exit code is $p.ExitCode" }',
//   ],
// }
// ```.
// Deprecated: Use `RunnerImageComponent` instead as this be internal soon.
type ImageBuilderComponent interface {
	awscdk.Resource
	// Component ARN.
	// Deprecated: Use `RunnerImageComponent` instead as this be internal soon.
	Arn() *string
	// The environment this resource belongs to.
	//
	// For resources that are created and managed in a Stack (those created by
	// creating new class instances like `new Role()`, `new Bucket()`, etc.), this
	// is always the same as the environment of the stack they belong to.
	//
	// For referenced resources (those obtained from referencing methods like
	// `Role.fromRoleArn()`, `Bucket.fromBucketName()`, etc.), they might be
	// different than the stack they were imported into.
	// Deprecated: Use `RunnerImageComponent` instead as this be internal soon.
	Env() *interfaces.ResourceEnvironment
	// The tree node.
	// Deprecated: Use `RunnerImageComponent` instead as this be internal soon.
	Node() constructs.Node
	// Returns a string-encoded token that resolves to the physical name that should be passed to the CloudFormation resource.
	//
	// This value will resolve to one of the following:
	// - a concrete value (e.g. `"my-awesome-bucket"`)
	// - `undefined`, when a name should be generated by CloudFormation
	// - a concrete name generated automatically during synthesis, in
	//   cross-environment scenarios.
	// Deprecated: Use `RunnerImageComponent` instead as this be internal soon.
	PhysicalName() *string
	// Supported platform for the component.
	// Deprecated: Use `RunnerImageComponent` instead as this be internal soon.
	Platform() *string
	// The stack in which this resource is defined.
	// Deprecated: Use `RunnerImageComponent` instead as this be internal soon.
	Stack() awscdk.Stack
	// Apply the given removal policy to this resource.
	//
	// The Removal Policy controls what happens to this resource when it stops
	// being managed by CloudFormation, either because you've removed it from the
	// CDK application or because you've made a change that requires the resource
	// to be replaced.
	//
	// The resource can be deleted (`RemovalPolicy.DESTROY`), or left in your AWS
	// account for data recovery and cleanup later (`RemovalPolicy.RETAIN`).
	// Deprecated: Use `RunnerImageComponent` instead as this be internal soon.
	ApplyRemovalPolicy(policy awscdk.RemovalPolicy)
	// Deprecated: Use `RunnerImageComponent` instead as this be internal soon.
	GeneratePhysicalName() *string
	// Returns an environment-sensitive token that should be used for the resource's "ARN" attribute (e.g. `bucket.bucketArn`).
	//
	// Normally, this token will resolve to `arnAttr`, but if the resource is
	// referenced across environments, `arnComponents` will be used to synthesize
	// a concrete ARN with the resource's physical name. Make sure to reference
	// `this.physicalName` in `arnComponents`.
	// Deprecated: Use `RunnerImageComponent` instead as this be internal soon.
	GetResourceArnAttribute(arnAttr *string, arnComponents *awscdk.ArnComponents) *string
	// Returns an environment-sensitive token that should be used for the resource's "name" attribute (e.g. `bucket.bucketName`).
	//
	// Normally, this token will resolve to `nameAttr`, but if the resource is
	// referenced across environments, it will be resolved to `this.physicalName`,
	// which will be a concrete name.
	// Deprecated: Use `RunnerImageComponent` instead as this be internal soon.
	GetResourceNameAttribute(nameAttr *string) *string
	// Grants read permissions to the principal on the assets buckets.
	// Deprecated: Use `RunnerImageComponent` instead as this be internal soon.
	GrantAssetsRead(grantee awsiam.IGrantable)
	// Deprecated: Use `RunnerImageComponent` instead as this be internal soon.
	PrefixCommandsWithErrorHandling(platform *string, commands *[]*string) *[]*string
	// Returns a string representation of this construct.
	// Deprecated: Use `RunnerImageComponent` instead as this be internal soon.
	ToString() *string
	// Applies one or more mixins to this construct.
	//
	// Mixins are applied in order. The list of constructs is captured at the
	// start of the call, so constructs added by a mixin will not be visited.
	// Use multiple `with()` calls if subsequent mixins should apply to added
	// constructs.
	//
	// Returns: This construct for chaining.
	// Deprecated: Use `RunnerImageComponent` instead as this be internal soon.
	With(mixins ...constructs.IMixin) constructs.IConstruct
}

// The jsii proxy struct for ImageBuilderComponent
type jsiiProxy_ImageBuilderComponent struct {
	internal.Type__awscdkResource
}

func (j *jsiiProxy_ImageBuilderComponent) Arn() *string {
	var returns *string
	_jsii_.Get(
		j,
		"arn",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_ImageBuilderComponent) Env() *interfaces.ResourceEnvironment {
	var returns *interfaces.ResourceEnvironment
	_jsii_.Get(
		j,
		"env",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_ImageBuilderComponent) Node() constructs.Node {
	var returns constructs.Node
	_jsii_.Get(
		j,
		"node",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_ImageBuilderComponent) PhysicalName() *string {
	var returns *string
	_jsii_.Get(
		j,
		"physicalName",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_ImageBuilderComponent) Platform() *string {
	var returns *string
	_jsii_.Get(
		j,
		"platform",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_ImageBuilderComponent) Stack() awscdk.Stack {
	var returns awscdk.Stack
	_jsii_.Get(
		j,
		"stack",
		&returns,
	)
	return returns
}


// Deprecated: Use `RunnerImageComponent` instead as this be internal soon.
func NewImageBuilderComponent(scope constructs.Construct, id *string, props *ImageBuilderComponentProperties) ImageBuilderComponent {
	_init_.Initialize()

	if err := validateNewImageBuilderComponentParameters(scope, id, props); err != nil {
		panic(err)
	}
	j := jsiiProxy_ImageBuilderComponent{}

	_jsii_.Create(
		"@cloudsnorkel/cdk-github-runners.ImageBuilderComponent",
		[]interface{}{scope, id, props},
		&j,
	)

	return &j
}

// Deprecated: Use `RunnerImageComponent` instead as this be internal soon.
func NewImageBuilderComponent_Override(i ImageBuilderComponent, scope constructs.Construct, id *string, props *ImageBuilderComponentProperties) {
	_init_.Initialize()

	_jsii_.Create(
		"@cloudsnorkel/cdk-github-runners.ImageBuilderComponent",
		[]interface{}{scope, id, props},
		i,
	)
}

// Checks if `x` is a construct.
//
// Use this method instead of `instanceof` to properly detect `Construct`
// instances, even when the construct library is symlinked.
//
// Explanation: in JavaScript, multiple copies of the `constructs` library on
// disk are seen as independent, completely different libraries. As a
// consequence, the class `Construct` in each copy of the `constructs` library
// is seen as a different class, and an instance of one class will not test as
// `instanceof` the other class. `npm install` will not create installations
// like this, but users may manually symlink construct libraries together or
// use a monorepo tool: in those cases, multiple copies of the `constructs`
// library can be accidentally installed, and `instanceof` will behave
// unpredictably. It is safest to avoid using `instanceof`, and using
// this type-testing method instead.
//
// Returns: true if `x` is an object created from a class which extends `Construct`.
// Deprecated: Use `RunnerImageComponent` instead as this be internal soon.
func ImageBuilderComponent_IsConstruct(x interface{}) *bool {
	_init_.Initialize()

	if err := validateImageBuilderComponent_IsConstructParameters(x); err != nil {
		panic(err)
	}
	var returns *bool

	_jsii_.StaticInvoke(
		"@cloudsnorkel/cdk-github-runners.ImageBuilderComponent",
		"isConstruct",
		[]interface{}{x},
		&returns,
	)

	return returns
}

// Returns true if the construct was created by CDK, and false otherwise.
// Deprecated: Use `RunnerImageComponent` instead as this be internal soon.
func ImageBuilderComponent_IsOwnedResource(construct constructs.IConstruct) *bool {
	_init_.Initialize()

	if err := validateImageBuilderComponent_IsOwnedResourceParameters(construct); err != nil {
		panic(err)
	}
	var returns *bool

	_jsii_.StaticInvoke(
		"@cloudsnorkel/cdk-github-runners.ImageBuilderComponent",
		"isOwnedResource",
		[]interface{}{construct},
		&returns,
	)

	return returns
}

// Check whether the given construct is a Resource.
// Deprecated: Use `RunnerImageComponent` instead as this be internal soon.
func ImageBuilderComponent_IsResource(construct constructs.IConstruct) *bool {
	_init_.Initialize()

	if err := validateImageBuilderComponent_IsResourceParameters(construct); err != nil {
		panic(err)
	}
	var returns *bool

	_jsii_.StaticInvoke(
		"@cloudsnorkel/cdk-github-runners.ImageBuilderComponent",
		"isResource",
		[]interface{}{construct},
		&returns,
	)

	return returns
}

func (i *jsiiProxy_ImageBuilderComponent) ApplyRemovalPolicy(policy awscdk.RemovalPolicy) {
	if err := i.validateApplyRemovalPolicyParameters(policy); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		i,
		"applyRemovalPolicy",
		[]interface{}{policy},
	)
}

func (i *jsiiProxy_ImageBuilderComponent) GeneratePhysicalName() *string {
	var returns *string

	_jsii_.Invoke(
		i,
		"generatePhysicalName",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (i *jsiiProxy_ImageBuilderComponent) GetResourceArnAttribute(arnAttr *string, arnComponents *awscdk.ArnComponents) *string {
	if err := i.validateGetResourceArnAttributeParameters(arnAttr, arnComponents); err != nil {
		panic(err)
	}
	var returns *string

	_jsii_.Invoke(
		i,
		"getResourceArnAttribute",
		[]interface{}{arnAttr, arnComponents},
		&returns,
	)

	return returns
}

func (i *jsiiProxy_ImageBuilderComponent) GetResourceNameAttribute(nameAttr *string) *string {
	if err := i.validateGetResourceNameAttributeParameters(nameAttr); err != nil {
		panic(err)
	}
	var returns *string

	_jsii_.Invoke(
		i,
		"getResourceNameAttribute",
		[]interface{}{nameAttr},
		&returns,
	)

	return returns
}

func (i *jsiiProxy_ImageBuilderComponent) GrantAssetsRead(grantee awsiam.IGrantable) {
	if err := i.validateGrantAssetsReadParameters(grantee); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		i,
		"grantAssetsRead",
		[]interface{}{grantee},
	)
}

func (i *jsiiProxy_ImageBuilderComponent) PrefixCommandsWithErrorHandling(platform *string, commands *[]*string) *[]*string {
	if err := i.validatePrefixCommandsWithErrorHandlingParameters(platform, commands); err != nil {
		panic(err)
	}
	var returns *[]*string

	_jsii_.Invoke(
		i,
		"prefixCommandsWithErrorHandling",
		[]interface{}{platform, commands},
		&returns,
	)

	return returns
}

func (i *jsiiProxy_ImageBuilderComponent) ToString() *string {
	var returns *string

	_jsii_.Invoke(
		i,
		"toString",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (i *jsiiProxy_ImageBuilderComponent) With(mixins ...constructs.IMixin) constructs.IConstruct {
	args := []interface{}{}
	for _, a := range mixins {
		args = append(args, a)
	}

	var returns constructs.IConstruct

	_jsii_.Invoke(
		i,
		"with",
		args,
		&returns,
	)

	return returns
}

